config/routes.rb
Bogo::Application.routes.draw do

  root 'welcome#index'

  namespace 'api' do
    resources :agebs, only: :index
  end
  
  get '/:locale' => 'welcome#index'
  get '/radius/:radius' => 'radius#index'
  
  get '/downloads/nota-metodologica' => 'downloads#note', :as => "download_note"
  get '/downloads/data' => 'downloads#data', :as => "download_data"
  

end

app/models/ageb.rb
##
#  Represents an Ageb entity with geo-statistical fields and a geometrical property 
#
class Ageb < ActiveRecord::Base
  include Geography
  
  ##
  #  The fields to use on the query for optimization
  #
  def selected_fields
    "gid, cvegeo, pob1, eco4, eco25, eco25_r, disc1, disc1_r, viv28, viv28_r, viv0, viv1, viv1_r, densidad, eco4_r, empleo, sup, empleo_r, nse, processed_geom, gmu"
  end
  
  def geometry_alias
    self.respond_to?(:the_geom) ? send(:the_geom) : send(:geom)
  end

  ##
  #  This method is on charge of pre-processing the_geom 
  #
  def prepare_geom
    return if self.geometry_alias.nil?
    
    factory = RGeo::GeoJSON::EntityFactory.instance
    feature = factory.feature(self.geometry_alias, nil, { 
        pob1: self.pob1,
        densidad: self.densidad,
        eco4_r: self.eco4_r,
        eco25_r: self.eco25_r,
        disc_r: self.disc1_r,
        viv0: self.viv0,
        viv1_r: self.viv1_r,
        viv28_r: self.viv28_r,
        nse: self.nse,
        gmu: self.gmu 
    })
    self.update_attribute(:processed_geom, RGeo::GeoJSON.encode(feature).inspect)
    p "Processed feature: #{self.gid}"
  end

  ##
  #  Evals the processed_geom text which is a stringified ruby hash
  #
  def coordinate_list
    eval(self.processed_geom)[0] || []
  end
  
  ##
  #  Bulk pre-processes all the agebs on this database
  #
  def self.process_geoms
    Ageb.all.each do |ageb|
      ageb.prepare_geom
    end
    
    p "Unprocessed features (marked for deletion): #{Ageb.where(:processed_geom => nil).count}"
    
    Ageb.where(:processed_geom => nil).map { |ageb| ageb.destroy }
  end
end

app/models/concerns/geography.rb
module Geography
  module ClassMethods
    
    def selected_fields
      "*"
    end
    
    def build_polygon_from_params(coordinates_)
      return nil if coordinates_.nil?
      return nil if (coordinates_[:sw].blank? || coordinates_[:ne].blank? || coordinates_[:ne] == "{}" || coordinates_[:sw] == "{}")
      lat_sw, lon_sw = coordinates_[:sw].split(',').map { |n| n.to_f }
      lat_ne, lon_ne = coordinates_[:ne].split(',').map { |n| n.to_f }

      geo_factory = RGeo::Cartesian.factory(srid: 4326)
      sw=geo_factory.point(lon_sw, lat_sw)
      ne=geo_factory.point(lon_ne, lat_ne)
      RGeo::Cartesian::BoundingBox.create_from_points(sw, ne).to_geometry
    end

    def filter_nearby(viewport)
      window=build_polygon_from_params(viewport)
      if self.respond_to?(:the_geom)
        self.select(selected_fields).where{st_intersects(the_geom, window)}
      else
        self.select(selected_fields).where{st_intersects(geom, window)}
      end
    end

    def find_nearby(viewport=nil)
      if viewport.nil?
        self.all
      else
        self.filter_nearby(viewport)
      end
    end
  end

  def apply_geo(coordinates)
    return self if coordinates.nil? || (coordinates["lon"].blank? || coordinates["lat"].blank?)
    self.coordinates = "POINT(#{coordinates["lon"].to_f} #{coordinates["lat"].to_f})"
    self
  end

  # Requires a path variable on the mixed-in class
  def to_points_list(style=:plain)
    points_list = style.eql?(:plain) ? String.new : Array.new
    return points_list if path.nil?
    path.points.each do |point|
      points_list << "#{point.y}|#{point.x} " if style.eql?(:plain)
      points_list << [point.y, point.x] if style.eql?(:json)
    end
    return points_list.chop if style.eql?(:plain)
    points_list
  end

  def lat
    coordinates.lat
  end

  def lon
    coordinates.lon
  end

  def coordinates_to_s
    %-"#{coordinates.to_s}"-
  end

  def self.included(base)
    base.extend(ClassMethods)
  end
end

app/controllers/api/agebs_controller.rb
##
#  API responder for AGEBS
#
class Api::AgebsController < ApplicationController
  
  respond_to :json
  
  ##
  #  Fetches the agebs visible on the current map viewport and responds with a JSON response
  #
  def index
    @agebs = Ageb.find_nearby(params[:viewport])
    respond_with(@agebs, :each_serializer => AgebSerializer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :set_locale

  def set_locale
   I18n.locale = (params[:locale] || :es_MX).to_sym
  end
end

app/controllers/downloads_controller.rb
##
#  Downloads controller
#
class DownloadsController < ApplicationController
  ##
  #  Allows the user to download the methodological note which was used for building the data used on this application
  #
  def note
    send_file Rails.root.join('public/Nota-metodologica-DOT.pdf'), :type => 'application/pdf', :disposition => 'inline'
  end
  
  ##
  #  Allows the user to download the data used on this application
  #
  def data
    send_file Rails.root.join('public/DOT-data.zip'), :type => 'application/zip', :disposition => 'inline'
  end

end

app/controllers/radius_controller.rb
##
#  Radius controller
#
class RadiusController < ApplicationController
  
  ##
  #  Replies with a JSON content depending on the selected radius (500,800, 1000, 2000)
  #
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dot DF - Desarrollo Orientado al Transporte</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	
  <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
  <link href='//api.tiles.mapbox.com/mapbox.js/v1.5.2/mapbox.css' rel='stylesheet' />
  <script src='//api.tiles.mapbox.com/mapbox.js/v1.5.2/mapbox.js'></script>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<script src="http://maps.google.com/maps/api/js?v=3&sensor=false"></script>
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-53721305-1', 'auto');
	  ga('send', 'pageview');

	</script>
	
</body>
</html>

app/views/welcome/_agebs.html.erb
<div class="stats-table layers-list">
	<div class="group">
		<p class="section-title"><%= t('app.sections.map.left_menu.aspects.population.title') %></p>
		<div class="feature" id="ageb_population-aspect">
			<div class="title"><%= t('app.sections.map.left_menu.aspects.total') %></div><div id="ageb_population" class="value">---</div>
		</div>
		<div class="feature" id="ageb_density-aspect">
			<div class="title"><%= t('app.sections.map.left_menu.aspects.population.hectare') %></div><div id="ageb_density" class="value">---</div>
		</div>
		<div class="feature" id="ageb_population_handicap-aspect">
			<div class="title"><%= t('app.sections.map.left_menu.aspects.population.handicapped') %></div><div id="ageb_population_handicap" class="value">---</div>
		</div>
		<div class="feature" id="ageb_population_with_job-aspect">
			<div class="title"><%= t('app.sections.map.left_menu.aspects.population.employed') %></div><div id="ageb_population_with_job" class="value">---</div>
		</div>
		<div class="feature" id="ageb_population_without_job-aspect">
			<div class="title"><%= t('app.sections.map.left_menu.aspects.population.unemployed') %></div><div id="ageb_population_without_job" class="value">---</div>
		</div>
	</div>

	<div class="group">
		<p class="section-title"><%= t('app.sections.map.left_menu.aspects.housing.title') %></p>
		<div class="feature" id="ageb_houses-aspect">
			<div class="title"><%= t('app.sections.map.left_menu.aspects.total') %></div><div id="ageb_houses" class="value">---</div>
		</div>
		<div class="feature" id="ageb_population_with_car-aspect">
			<div class="title"><%= t('app.sections.map.left_menu.aspects.housing.with_car') %></div><div id="ageb_population_with_car" class="value">---</div>
		</div>
		<div class="feature" id="ageb_houses_empty-aspect">
			<div class="title"><%= t('app.sections.map.left_menu.aspects.housing.unoccupied') %></div><div id="ageb_houses_empty" class="value">---</div>
		</div>
	</div>

	<div class="group">
		<p class="section-title"><%= t('app.sections.map.left_menu.aspects.others.title') %></p>
		<div class="feature" id="ageb_socioeconomic_level-aspect">
			<div class="title"><%= t('app.sections.map.left_menu.aspects.others.socioeconomic_level') %></div><div id="ageb_socioeconomic_level" class="value">---</div>
		</div>
		<div class="feature" id="ageb_margination-aspect">
			<div class="title"><%= t('app.sections.map.left_menu.aspects.others.margination_level') %></div><div id="ageb_margination" class="value">---</div>
		</div>
	</div>

	<p class="usage-note"><%= t('app.sections.map.left_menu.aspects.usage_notes') %></p>
	<div id="heatmap-placeholder"></div>
	<%= render 'heat_map' %>
</div>

app/views/welcome/_heat_map.html.erb
<div id="heatmap-container" class="hidden">
	<div id="heatmap">
		<h4><%= t('app.sections.map.heatmap.title') %></h4>
		<ul class="range"><li class="colored"> <span class="color-box yellow-pale"> </span> </li><li class="text yellow-pale-field"> 0 - 20</li></ul>
		<ul class="range"><li class="colored"> <span class="color-box yellow"> </span> </li><li class="text yellow-field"> 21 - 30</li></ul>
		<ul class="range"><li class="colored"> <span class="color-box orange"> </span> </li><li class="text orange-field"> 31 - 90</li></ul>
		<ul class="range"><li class="colored"> <span class="color-box red"> </span> </li><li class="text red-field"> 91 - 200</li></ul>
		<ul class="range"><li class="colored"> <span class="color-box dark-red"> </span> </li><li class="text dark-red-field"> 201 - 1209</li></ul>
	</div>
	
	<p>
		<a href="javascript:void(0);" id="dismiss-heatmap-container">
			<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;
			<%= t('app.sections.map.heatmap.back') %>
		</a>
	</p>
	
</div>

app/views/welcome/_map_section.html.erb
<div class="container-panel">	
	<div class="content">
		<div id="polygons" class="transitable">
			<div class="panel-section blue">
				<p class="title"><%= t('app.sections.map.left_menu.title') %></p>
				<p class="icon-section" data-toggle="tooltip" data-placement="top" title="<%= t('app.sections.map.left_menu.title') %>">
					<%= link_to image_tag('polygons.png', :size => '45x45'), 'javascript:void(0);', :class => 'toggler', :id => 'polygons-t' %>
				</p>
			</div>

			<div class="panel">
				<%= render 'welcome/radius' %>
	
				<div id="stats-panel" class="agebs hidden">
					<div class="separator"></div>
					<%= render 'welcome/agebs' %>
				</div>
			</div>
		</div>
	</div>
	
</div>
<div class="bottom-area">
	<div class="container">
		<div class="controls controls-generic toggable-panel">
			<br>
			<p class="icon-section" data-toggle="tooltip" data-placement="top" title="<%= t('app.sections.map.bottom_menu.titles.menu') %>">
				<%= link_to image_tag('menu.png', :size => '45x45'), 'javascript:void(0);', :class => 'toggler', :id => 'map-t' %>
			</p>
			<p class="title"><%= t('app.sections.map.bottom_menu.titles.menu') %></p>
		</div>
		<div class="panel-mini toggable-panel">
			<ul>
				<li><%= link_to t('app.sections.map.bottom_menu.options.satellite'), 'javascript:void(0);', :class => 'show-satellite' %></li>
				<li class="hidden"><%= link_to t('app.sections.map.bottom_menu.options.plain'), 'javascript:void(0);', :class => 'show-carto' %></li>
				
				<li class="hidden polygons-enabler-off"><%= link_to t('app.sections.map.bottom_menu.options.radius.hide'), 'javascript:void(0);', :class => 'polygons-off' %></li>
				<li class="hidden polygons-enabler-on"><%= link_to t('app.sections.map.bottom_menu.options.radius.show'), 'javascript:void(0);', :class => 'polygons-on' %></li>				
			</ul>
		</div>
		<div class="controls toggable-panel">
			<br>
			<p class="icon-section" data-toggle="tooltip" data-placement="top" title="<%= t('app.sections.map.bottom_menu.titles.network') %>">
				<%= link_to image_tag('network.png', :size => '45x45'), 'javascript:void(0);', :class => 'toggler', :id => 'map-t' %>
			</p>
			<p class="title"><%= t('app.sections.map.bottom_menu.titles.network') %></p>
		</div>
		<div class="panel toggable-panel">
			<%= render 'welcome/network' %>
		</div>
		<div class="control-minimizer">
			<%= link_to image_tag('minimize.png', :size => '35x35'), 'javascript:void(0);', :id => 'minimizer' %>
			<%= link_to image_tag('maximize.png', :size => '35x35'), 'javascript:void(0);', :class => 'hidden', :id => 'maximizer' %>
		</div>
	</div>
</div>
<div id='map-basic'></div>

app/views/welcome/_menu.html.erb
<div class="menu">
	<ul>
		<li class="spinner hidden"><%= image_tag('loader.gif') %></li>
		<li class="head"><%= link_to t('app.menu.start'), '#main', :class => selected[:main] %></li>
		<li><%= link_to t('app.menu.map'), '#map', :class => selected[:map] %></li>
		<li><%= link_to t('app.menu.dot'), '#dot', :class => selected[:dot] %></li>
		<li><%= link_to t('app.menu.about'), '#about', :class => selected[:about] %></li>
		<% if I18n.locale == I18n.default_locale %>
			<li><%= link_to t('app.menu.lang.english'), :locale => 'en' %></li>
		<% else %>
			<li><%= link_to t('app.menu.lang.spanish'), :locale => 'es_MX' %></li>
		<% end %>
	</ul>
</div>

app/views/welcome/_network.html.erb
<ul class="transports-list">
	<li class="transport-layer layer" data-toggle="tooltip" data-placement="top" title="STC Metro">
		<p><a href="javascript:void(0);" id="metro"><span class="pic"><%= image_tag('metro.png', :size => '60x60') %></span></a></p>
	</li>
	<li class="transport-layer layer" data-toggle="tooltip" data-placement="top" title="Metrobús">
		<p><a href="javascript:void(0);" id="metrobus"><span class="pic"><%= image_tag('metrobus.png', :size => '60x60') %></span></a></p>
	</li>
	<li class="transport-layer layer" data-toggle="tooltip" data-placement="top" title="Transportes Eléctricos">
		<p><a href="javascript:void(0);" id="transporteselectricos"><span class="pic"><%= image_tag('transporteselectricos.png', :size => '60x60') %></span></a></p>
	</li>
	<li class="transport-layer layer" data-toggle="tooltip" data-placement="top" title="Tren Suburbano">
		<p><a href="javascript:void(0);" id="trensuburbano"><span class="pic"><%= image_tag('suburbano.jpg', :size => '60x60') %></span></a></p>
	</li>
	<li class="transport-layer layer" data-toggle="tooltip" data-placement="top" title="Mexibus">
		<p><a href="javascript:void(0);" id="mexibus"><span class="pic"><%= image_tag('mexi-bus.png', :size => '60x60') %></span></a></p>
	</li>
	<li class="transport-layer layer" data-toggle="tooltip" data-placement="top" title="Propuestas del ITDP">
		<p><a href="javascript:void(0);" id="itdp"><span class="pic"><%= image_tag('ITDP-square-mini.png') %></span></a></p>
	</li>
</ul>

app/views/welcome/_radius.html.erb
<div class="radius-header">
	<div class="select-radius">
		<p class="title"><%= t('app.sections.map.left_menu.subtitle') %></p>
		<div class="separator"></div>
		<ul class="radius-list">
			<li class="layer">
				<a href="javascript:void(0);" id="agebs-radius-all" data-size="all" class="polygon-layer radius">
					<span class="name"><%= t('app.sections.map.left_menu.options.all') %></span>
				</a>
			</li>
			<li class="layer">
				<a href="javascript:void(0);" id="agebs-radius-500" data-size="500" class="polygon-layer radius">
					<span class="name"><%= t('app.sections.map.left_menu.options.five') %></span>
				</a>
			</li>
			<li class="layer">
				<a href="javascript:void(0);" id="agebs-radius-800" data-size="800" class="polygon-layer radius">
					<span class="name"><%= t('app.sections.map.left_menu.options.eight') %></span>
				</a>
			</li>
			<li class="layer">
				<a href="javascript:void(0);" id="agebs-radius-1000" data-size="1000" class="polygon-layer radius">
					<span class="name"><%= t('app.sections.map.left_menu.options.onet') %></span>
				</a>
			</li>
			<li class="layer">
				<a href="javascript:void(0);" id="agebs-radius-2000" data-size="2000" class="polygon-layer radius">
					<span class="name"><%= t('app.sections.map.left_menu.options.twot') %></span>
				</a>
			</li>
		</ul>
	</div>
</div>

<div class="radius-options hidden">
	<div class="500-message alert alert-info alert-dismissable">
	  <button type="button" class="close radius-close" data-dismiss="alert" aria-hidden="true">&times;</button>
	  <%= t('app.sections.map.left_menu.selections.five').html_safe %>
	</div>
	<div class="800-message alert alert-info alert-dismissable">
	  <button type="button" class="close radius-close" data-dismiss="alert" aria-hidden="true">&times;</button>
	  <%= t('app.sections.map.left_menu.selections.eight').html_safe %>
	</div>
	<div class="1000-message alert alert-info alert-dismissable">
	  <button type="button" class="close radius-close" data-dismiss="alert" aria-hidden="true">&times;</button>
	  <%= t('app.sections.map.left_menu.selections.onet').html_safe %>
	</div>
	<div class="2000-message alert alert-info alert-dismissable">
	  <button type="button" class="close radius-close" data-dismiss="alert" aria-hidden="true">&times;</button>
	  <%= t('app.sections.map.left_menu.selections.twot').html_safe %>
	</div>
	<div class="all-message alert alert-info alert-dismissable">
	  <button type="button" class="close radius-close" data-dismiss="alert" aria-hidden="true">&times;</button>
	  <%= t('app.sections.map.left_menu.selections.all').html_safe %>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="section main-section" data-anchor="main">
	<div class="background-art"><%= image_tag('map-dot.png', alt: t('attributions.blueprint_icon'), title: t('attributions.blueprint_icon')) %></div>

	<div class="core-image"></div>
	<%= render :partial => 'welcome/menu', :locals => {:selected => { :main => "selected" }} %>
	<div class="scontent">
		<p class="title"><%= t('app.sections.start.title') %></p>

		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-6 col-md-4">
					<p class="core"><%= t('app.sections.start.core') %></p>
					<p class="action"><%= link_to t('app.sections.start.action'), root_path.concat('#map'), :class => "call-to-action" %></p>
				</div>
				<div class="col-xs-6 col-md-4">
					<p class="intro"><%= t('app.sections.start.intro').html_safe %></p>
				</div>
				<div class="col-xs-6 col-md-4"><%= image_tag('df-logo.png') %></div>
			</div>
		</div>
	</div>
</div>

<div class="section map-section" data-anchor="map">
	<p id="transport-radius" class="hidden"><%= t('app.sections.map.popups.nearby').html_safe %></p>
	<%= render :partial => 'welcome/menu', :locals => {:selected => { :map => "selected" }} %>
	<div class="container">
		<%= render :partial => 'welcome/map_section' %>
	</div>
	<div class="right-positioned">

	</div>
</div>

<div class="section dot-section" data-anchor="dot">
	<%= render :partial => 'welcome/menu', :locals => {:selected => { :dot => "selected" }} %>
	<div class="background-art"><%= image_tag('train-icon.png', alt: t('attributions.train_icon'), title: t('attributions.train_icon')) %></div>

	<div class="scontent">

		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-12 col-md-8">
					<iframe class="youtube-player" type="text/html" width="650" height="450" src="http://www.youtube.com/embed/8IsU0RdgPCw" allowfullscreen frameborder="0">
					</iframe>
				</div>
				<div class="col-xs-12 col-md-4">
					<p class="intro"><%= t('app.sections.dot.intro').html_safe %></p>
					<p class="action"><%= link_to t('app.sections.dot.action'), root_path.concat('#map'), :class => "call-to-action" %></p>
				</div>
			</div>
		</div>

	</div>
</div>

<div class="section about-section" data-anchor="about">
	<%= render :partial => 'welcome/menu', :locals => {:selected => { :about => "selected" }} %>

	<div class="background-art"><%= image_tag('blueprint-icon.png', alt: t('attributions.building_icon'), title: t('attributions.building_icon')) %></div>

	<div class="scontent">

		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-7 col-md-5 supporters">
					<div class="box">
						<h3><%= t('app.sections.about.thanks_to') %></h3>
						<ul class="thanks-to">
							<li><%= link_to image_tag('uk_embassy_logo.png'), 'https://www.gov.uk/government/world/organisations/british-embassy-mexico-city.es-419', target: "_blank" %></li>
							<br><br/>
							<li><%= link_to image_tag('ITDP-small.png'), 'http://itdp.mx', target: "_blank" %></li>
						</ul>
					</div>

				</div>
				<div class="col-xs-11 col-md-7 developers">
					<div class="box">
						<h3><%= t('app.sections.about.dedication_of') %></h3>
						<ul class="dedication-of">
							<li>
								<div class="person">
									<p class="title">Salvador Medina</p>
									<p class="subtitle"><%= t('app.sections.about.team.coordination') %></p>
								</div>
							</li>
							<li>
								<div class="person">
									<p class="title">Alejandro Cruz</p>
									<p class="subtitle"><%= t('app.sections.about.team.web_development') %></p>
								</div>
							</li>
							<li>
								<div class="person">
									<p class="title">Nely Patlán</p>
									<p class="subtitle"><%= t('app.sections.about.team.data_selection') %></p>
								</div>
							</li>
							<li>
								<div class="person">
									<p class="title">Santiago Fernández</p>
									<p class="subtitle"><%= t('app.sections.about.team.estimations') %></p>
								</div>
							</li>
						</ul>
					</div>
					<div class="box box-downloads">
						<h3><%= t('app.sections.about.download_section') %></h3>
						<br>
						<ul>
							<li><%= image_tag('note-icon.png', size: '40x40', alt: t('attributions.note_icon'), title: t('attributions.note_icon')) %>
							<%= link_to t('app.sections.about.methodological_note'), download_note_path, :target => "_blank" %></li>
							<li><%= image_tag('download-icon.png', :size => '40x40', alt: t('attributions.download_icon'), title: t('attributions.download_icon')) %> 
							<%= link_to t('app.sections.about.data'), download_data_path, :target => "_blank" %></li>
							<li>
								<%= image_tag('proposal-icon.png', :size => '40x40', alt: t('attributions.proposal_icon'), title: t('attributions.proposal_icon')) %> 
								<%= link_to t('app.sections.about.proposal'), 'http://mexico.itdp.org/documentos/hacia-una-estrategia-de-desarrollo-orientado-al-transporte-para-el-distrito-federal/', :target => "_blank" %>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>

	</div>


	<div class="bar">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-24 col-md-12">
					<ul>
						<li><p>Av. México 69 Col. Hipódromo Condesa Del. Cuauhtémoc México DF, C.P. 06100</p></li>
						<li><a href="mailto:mexico@itdp.org" target="_top">mexico@itdp.org</a></li>
						<li class="smaller"><p>+52 (55) 3626-2963  +52 (55) 3626-2964</p></li>
						<li class="social">
							<%= link_to image_tag('twitter.png', :size => '30x30'), 'https://twitter.com/ITDPmx', :target => "_blank" %> 
							<%= link_to image_tag('facebook.png', :size => '30x30'), 'http://www.facebook.com/itdpmx', :target => "_blank" %>
						</li>
					</ul>
				</div>
			</div>
		</div>

	</div>
</div>